/* EpoxyMitra language layer. Translates both initial markup and views rendered later by app.js. */
(() => {
  'use strict';
  const KEY='epoxy-aura-language';
  const hi={
    'Language':'भाषा','Select language':'भाषा चुनें','English':'अंग्रेज़ी','Skip to content':'मुख्य सामग्री पर जाएँ','Toggle navigation':'नेविगेशन खोलें/बंद करें','Main navigation':'मुख्य नेविगेशन','Switch color theme':'रंग थीम बदलें','Close dialog':'संवाद बंद करें',
    'Home':'होम','Services':'सेवाएँ','Gallery':'गैलरी','Learning':'प्रशिक्षण','Estimator':'लागत अनुमान','Contact':'संपर्क','More':'और','About us':'हमारे बारे में','Design collection':'डिज़ाइन संग्रह','Pricing':'मूल्य','Learning plans':'प्रशिक्षण योजनाएँ','Training schedule':'प्रशिक्षण समय-सारणी','Video consultation':'वीडियो परामर्श','Get a quote':'कोटेशन पाएँ','FAQs':'सामान्य प्रश्न','Privacy & enquiries':'गोपनीयता और पूछताछ','Local admin':'स्थानीय एडमिन','All rights reserved.':'सर्वाधिकार सुरक्षित।',
    'Art Your Own Kingdom':'अपना साम्राज्य स्वयं सजाएँ','ART YOUR OWN KINGDOM':'अपना साम्राज्य स्वयं सजाएँ','Epoxy flooring':'एपॉक्सी फ्लोरिंग','Consultation':'परामर्श','Resin furniture':'रेज़िन फर्नीचर','Call to confirm the exact entrance before visiting.':'आने से पहले सही प्रवेश-द्वार की पुष्टि के लिए कॉल करें।','Open location in Google Maps ↗':'Google Maps में स्थान खोलें ↗',
    'Chat on WhatsApp ↗':'WhatsApp पर चैट करें ↗','How can we help?':'हम आपकी कैसे मदद कर सकते हैं?','Choose your enquiry topic. You can review the message in WhatsApp before sending.':'अपनी पूछताछ का विषय चुनें। भेजने से पहले आप WhatsApp में संदेश देख सकते हैं।','Enquiry regarding':'पूछताछ का विषय','Your question (optional)':'आपका प्रश्न (वैकल्पिक)','Continue to WhatsApp ↗':'WhatsApp पर आगे बढ़ें ↗','A draft opens; no message is sent automatically.':'एक ड्राफ्ट खुलेगा; कोई संदेश अपने-आप नहीं भेजा जाएगा।',
    'Epoxy flooring':'एपॉक्सी फ्लोरिंग','Glitter dining table':'ग्लिटर डाइनिंग टेबल','Illuminated table':'रोशनी वाली टेबल','Flower or star table':'फूल या सितारा टेबल','Custom epoxy design':'कस्टम एपॉक्सी डिज़ाइन','Online course':'ऑनलाइन कोर्स','Offline training':'ऑफलाइन प्रशिक्षण','Other enquiry':'अन्य पूछताछ',
    'Kolkata weather':'कोलकाता मौसम','Forecast ↗':'पूर्वानुमान ↗','Weather info':'मौसम जानकारी','Waiting for weather data.':'मौसम जानकारी की प्रतीक्षा है।','Weather is a model estimate for Kolkata, not a site measurement. Internet access is required.':'मौसम कोलकाता के लिए मॉडल अनुमान है, स्थल माप नहीं। इंटरनेट आवश्यक है।','Pause effects':'इफेक्ट रोकें','Resume effects':'इफेक्ट चालू करें',
    'Quick guides':'त्वरित वीडियो गाइड','Minimise guides':'गाइड छोटा करें','Video guides':'वीडियो गाइड','Customer Guide':'ग्राहक गाइड','Student Guide':'विद्यार्थी गाइड','Customer Guide Video':'ग्राहक गाइड वीडियो','Student Guide Video':'विद्यार्थी गाइड वीडियो','Play video':'वीडियो चलाएँ','Browse designs, check prices and send an enquiry.':'डिज़ाइन देखें, कीमत जाँचें और पूछताछ भेजें।','Explore courses, fees and registration.':'कोर्स, फीस और पंजीकरण देखें।','This guide video is currently unavailable.':'यह गाइड वीडियो अभी उपलब्ध नहीं है।',
    'Overview':'अवलोकन','Homepage media':'होमपेज मीडिया','Guide videos':'गाइड वीडियो','Courses':'कोर्स','Course plans':'कोर्स योजनाएँ','Design services':'डिज़ाइन सेवाएँ','Batches & seats':'बैच और सीटें','Discounts':'छूट','Estimator rates':'अनुमान दरें','Enquiry inbox':'पूछताछ इनबॉक्स','Customers':'ग्राहक','Students':'विद्यार्थी','Categories':'श्रेणियाँ','Reports':'रिपोर्ट','Business settings':'व्यवसाय सेटिंग्स','Studio workspace':'स्टूडियो कार्यक्षेत्र','Manage your local catalogue, training and enquiries.':'अपने स्थानीय कैटलॉग, प्रशिक्षण और पूछताछ का प्रबंधन करें।',
    'These settings control the two floating video guides. Upload, replace, rename or disable either guide without editing source code.':'ये सेटिंग दोनों फ्लोटिंग वीडियो गाइड नियंत्रित करती हैं। स्रोत कोड बदले बिना वीडियो अपलोड, बदलें, नाम दें या बंद करें।','Enable this video':'यह वीडियो चालू रखें','Video title':'वीडियो शीर्षक','Video URL / asset path':'वीडियो URL / एसेट पथ','Short description':'संक्षिप्त विवरण','Upload replacement video (MP4/WebM, max 2 MB)':'बदला हुआ वीडियो अपलोड करें (MP4/WebM, अधिकतम 2 MB)','Save guide videos':'गाइड वीडियो सहेजें','View guides':'गाइड देखें','Guide videos saved.':'गाइड वीडियो सहेजे गए।','Videos must be MP4 or WebM and no larger than 2 MB.':'वीडियो MP4 या WebM और 2 MB से बड़ा नहीं होना चाहिए।','Each enabled guide needs a title, description and video.':'हर चालू गाइड के लिए शीर्षक, विवरण और वीडियो आवश्यक है।',
    'Beginner':'शुरुआती','Intermediate':'मध्यम','Advanced':'उन्नत','Online':'ऑनलाइन','Offline':'ऑफलाइन','Online & Offline':'ऑनलाइन और ऑफलाइन','Duration':'अवधि','Price':'मूल्य','Original price':'मूल मूल्य','Offer price':'ऑफर मूल्य','Discount':'छूट','Level':'स्तर','Mode':'माध्यम','Details':'विवरण','View details':'विवरण देखें','Join / enquire':'जुड़ें / पूछताछ करें','Enquire now':'अभी पूछताछ करें','Learn more':'और जानें','Book consultation':'परामर्श बुक करें','Contact us':'हमसे संपर्क करें','Call now':'अभी कॉल करें','WhatsApp':'WhatsApp','Email':'ईमेल','Address':'पता','Business hours':'व्यवसाय समय',
    'Plain Design':'सादा एपॉक्सी डिज़ाइन','Mix Design':'मिश्रित एपॉक्सी डिज़ाइन','3D Design':'3D एपॉक्सी डिज़ाइन','3D Design with Lighting':'लाइटिंग सहित 3D एपॉक्सी डिज़ाइन','Complete Home Interior':'संपूर्ण होम इंटीरियर','Bedroom Design':'बेडरूम डिज़ाइन','Living Room Design':'लिविंग रूम डिज़ाइन','Kitchen Design':'किचन डिज़ाइन','Bathroom Design':'बाथरूम डिज़ाइन','Office Design':'ऑफिस डिज़ाइन','Furniture Design':'फर्नीचर डिज़ाइन','Other Room & Furniture Designs':'अन्य कमरे और फर्नीचर डिज़ाइन',
    'Name':'नाम','Mobile number':'मोबाइल नंबर','Phone number':'फोन नंबर','Message':'संदेश','Enquiry type':'पूछताछ प्रकार','Selected course / design':'चुना हुआ कोर्स / डिज़ाइन','Submit enquiry':'पूछताछ भेजें','Customer enquiry':'ग्राहक पूछताछ','Course enquiry':'कोर्स पूछताछ','Online course enquiry':'ऑनलाइन कोर्स पूछताछ','Offline course enquiry':'ऑफलाइन कोर्स पूछताछ','Custom design enquiry':'कस्टम डिज़ाइन पूछताछ','Required':'आवश्यक','Optional':'वैकल्पिक','Please enter your name.':'कृपया अपना नाम दर्ज करें।','Please enter a valid mobile number.':'कृपया सही मोबाइल नंबर दर्ज करें।','Please select an enquiry type.':'कृपया पूछताछ का प्रकार चुनें।','Your enquiry has been saved.':'आपकी पूछताछ सहेज ली गई है।',
    'What could your project cost?':'आपके प्रोजेक्ट की लागत कितनी हो सकती है?','Measure your space, choose a finish and explore a practical budget.':'अपनी जगह मापें, फिनिश चुनें और व्यावहारिक बजट जानें।','Your project':'आपका प्रोजेक्ट','Epoxy finish':'एपॉक्सी फिनिश','Your spaces':'आपकी जगहें','Area unit':'क्षेत्र इकाई','Square feet':'वर्ग फुट','Square metres':'वर्ग मीटर','Add another space':'एक और जगह जोड़ें','Surface & design choices':'सतह और डिज़ाइन विकल्प','Additional preparation':'अतिरिक्त तैयारी','Design detail':'डिज़ाइन विवरण','Standard design':'मानक डिज़ाइन','Protective finish upgrade':'सुरक्षात्मक फिनिश अपग्रेड','Budget allowances':'बजट प्रावधान','Your available budget (optional, ₹)':'आपका उपलब्ध बजट (वैकल्पिक, ₹)','Your indicative project budget':'आपका अनुमानित प्रोजेक्ट बजट','Where the budget goes':'बजट का विवरण','Discuss this estimate ↗':'इस अनुमान पर चर्चा करें ↗','Print / save PDF':'प्रिंट / PDF सहेजें','Download details':'विवरण डाउनलोड करें','Open estimate in WhatsApp ↗':'अनुमान WhatsApp में खोलें ↗','Compare your options':'विकल्पों की तुलना करें','How this estimate is calculated':'यह अनुमान कैसे निकाला गया','Planning estimate only.':'केवल योजना हेतु अनुमान।',
    'Search':'खोजें','All':'सभी','Filter':'फ़िल्टर','Find your inspiration':'अपनी प्रेरणा खोजें','View concept ↗':'कॉन्सेप्ट देखें ↗','Design concept':'डिज़ाइन कॉन्सेप्ट','unique concepts':'विशिष्ट कॉन्सेप्ट','No results found.':'कोई परिणाम नहीं मिला।','No courses match these filters.':'इन फ़िल्टर से कोई कोर्स नहीं मिला।','View homepage':'होमपेज देखें','Save homepage media':'होमपेज मीडिया सहेजें','Showcase images':'शोकेस चित्र','Add image':'चित्र जोड़ें','Show':'दिखाएँ','Category':'श्रेणी','Caption':'कैप्शन','Remove':'हटाएँ','Save':'सहेजें','Cancel':'रद्द करें','Edit':'संपादित करें','Delete':'हटाएँ','Manage':'प्रबंधित करें','Status':'स्थिति','New':'नया','Contacted':'संपर्क किया','Confirmed':'पुष्टि हुई','Closed':'बंद','Cancelled':'रद्द',
    'Craft with a point of view.':'एक विशिष्ट सोच के साथ कला।','About EpoxyMitra':'EpoxyMitra के बारे में','Art meets a practical surface.':'कला और उपयोगी सतह का संगम।','One material. Many possibilities.':'एक सामग्री। अनेक संभावनाएँ।','Floor finishes, thoughtfully selected':'सोच-समझकर चुनी गई फ्लोर फिनिश','Designed for the people who use it.':'उपयोग करने वालों के लिए डिज़ाइन।','How we work':'हम कैसे काम करते हैं','For your space':'आपकी जगह के लिए','For your practice':'आपके काम के लिए','For your next skill':'आपके अगले कौशल के लिए','Homeowners & businesses':'घर मालिक और व्यवसाय','Designers & contractors':'डिज़ाइनर और ठेकेदार','Learners & applicators':'शिक्षार्थी और एप्लीकेटर',
    'The EpoxyMitra gallery.':'EpoxyMitra गैलरी।','Explore flooring, glitter, light, florals and resin furniture.':'फ्लोरिंग, ग्लिटर, लाइट, फूलों के डिज़ाइन और रेज़िन फर्नीचर देखें।','Find your next course':'अपना अगला कोर्स चुनें','Choose your learning path.':'अपना प्रशिक्षण मार्ग चुनें।','Individual courses':'व्यक्तिगत कोर्स','Complete learning plans':'पूर्ण प्रशिक्षण योजनाएँ','Available batches':'उपलब्ध बैच','Seat availability':'सीट उपलब्धता','No scheduled batches are currently published.':'अभी कोई निर्धारित बैच प्रकाशित नहीं है।',
    'Data changed in another tab. Reload this page before saving to avoid overwriting newer changes.':'डेटा दूसरे टैब में बदल गया है। नया डेटा मिटने से बचाने के लिए पेज फिर लोड करें।','Saved data could not be read. The business catalogue is shown; existing browser data has not been overwritten.':'सहेजा डेटा पढ़ा नहीं जा सका। व्यवसाय कैटलॉग दिखाया गया है; पुराना ब्राउज़र डेटा नहीं बदला गया।','This application requires JavaScript. Please enable it in your browser.':'इस एप्लिकेशन के लिए JavaScript आवश्यक है। कृपया ब्राउज़र में इसे चालू करें।'
  };
  const phrases=Object.entries(hi).sort((a,b)=>b[0].length-a[0].length);
  const textState=new WeakMap(),attrState=new WeakMap();
  let language=localStorage.getItem(KEY)==='hi'?'hi':'en';
  const skip=node=>{const el=node.nodeType===1?node:node.parentElement;return !el||el.closest('[data-no-translate],#print-estimate,script,style,code,pre,video,source,iframe');};
  function translate(source){
    if(language==='en'||!source.trim())return source;
    const leading=source.match(/^\s*/)[0],trailing=source.match(/\s*$/)[0],core=source.trim();
    if(hi[core])return leading+hi[core]+trailing;
    let output=core;
    for(const [en,value] of phrases)if(en.length>3&&output.includes(en))output=output.split(en).join(value);
    output=output.replace(/^(\d+) courses$/i,'$1 कोर्स').replace(/^(\d+) unique concepts$/i,'$1 विशिष्ट कॉन्सेप्ट').replace(/^(\d+) seats? left$/i,'$1 सीट शेष').replace(/\b(\d+) hours?\b/gi,'$1 घंटे').replace(/\b(\d+) days?\b/gi,'$1 दिन').replace(/\b(\d+) weeks?\b/gi,'$1 सप्ताह');
    return leading+output+trailing;
  }
  function textNode(node){
    if(skip(node)||!node.nodeValue.trim())return;
    let state=textState.get(node),current=node.nodeValue;
    if(!state||current!==state.rendered)state={source:current,rendered:current};
    const rendered=language==='en'?state.source:translate(state.source);state.rendered=rendered;textState.set(node,state);if(current!==rendered)node.nodeValue=rendered;
  }
  function attributes(el){
    if(skip(el))return;
    const names=['placeholder','title','aria-label'];let states=attrState.get(el)||{};
    for(const name of names)if(el.hasAttribute(name)){const current=el.getAttribute(name);let state=states[name];if(!state||current!==state.rendered)state={source:current,rendered:current};const rendered=language==='en'?state.source:translate(state.source);state.rendered=rendered;states[name]=state;if(current!==rendered)el.setAttribute(name,rendered);}
    attrState.set(el,states);
  }
  function apply(root=document.body){
    if(root.nodeType===3){textNode(root);return;}
    if(root.nodeType!==1&&root.nodeType!==9)return;
    if(root.nodeType===1)attributes(root);
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let node;
    while((node=walker.nextNode()))node.nodeType===3?textNode(node):attributes(node);
    document.documentElement.lang=language==='hi'?'hi':'en';
  }
  function setLanguage(value){language=value==='hi'?'hi':'en';localStorage.setItem(KEY,language);const select=document.getElementById('language-select');if(select)select.value=language;apply();document.dispatchEvent(new CustomEvent('epoxy:languagechange',{detail:{language}}));}
  const observer=new MutationObserver(records=>{for(const record of records){if(record.type==='characterData')textNode(record.target);else if(record.type==='attributes')attributes(record.target);else for(const node of record.addedNodes)apply(node);}});
  document.addEventListener('DOMContentLoaded',()=>{const select=document.getElementById('language-select');select.value=language;select.addEventListener('change',event=>setLanguage(event.target.value));apply();observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']});});
  window.EpoxyI18n={get language(){return language;},setLanguage,translate,apply};
})();
